version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-net

  authservice:
    image: auth-service
    container_name: authservice
    depends_on:
      - rabbitmq
    ports:
      - "5067:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql-express.c1auaee86hty.ap-south-1.rds.amazonaws.com,1433;Database=AuthDb;User Id=adminuser;Password=9745219418dD;TrustServerCertificate=True;
      - Jwt__Key=THIS_IS_A_LONG_SUPER_SECRET_KEY_1234567890_ABCDEF
      - Jwt__Issuer=authservice
      - Jwt__Audience=auth_clients
      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=guest
      - RabbitMq__Password=guest
    networks:
      - ecommerce-net

  userservice:
    image: user-service
    container_name: userservice
    depends_on:
      - rabbitmq
      - authservice
    ports:
      - "5031:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql-express.c1auaee86hty.ap-south-1.rds.amazonaws.com,1433;Database=UserDb;User Id=adminuser;Password=9745219418dD;TrustServerCertificate=True;
      - Jwt__Key=THIS_IS_A_LONG_SUPER_SECRET_KEY_1234567890_ABCDEF
      - Jwt__Issuer=authservice
      - Jwt__Audience=auth_clients
      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=guest
      - RabbitMq__Password=guest
    networks:
      - ecommerce-net

  productservice:
    image: product-service
    container_name: productservice
    depends_on:
      - rabbitmq
      - authservice
    ports:
      - "5214:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql-express.c1auaee86hty.ap-south-1.rds.amazonaws.com,1433;Database=ProductDb;User Id=adminuser;Password=9745219418dD;TrustServerCertificate=True;
      - Jwt__Key=THIS_IS_A_LONG_SUPER_SECRET_KEY_1234567890_ABCDEF
      - Jwt__Issuer=authservice
      - Jwt__Audience=auth_clients
      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=guest
      - RabbitMq__Password=guest
    networks:
      - ecommerce-net

  gateway:
    image: api-gateway
    container_name: gateway
    depends_on:
      - authservice
      - userservice
      - productservice
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=THIS_IS_A_LONG_SUPER_SECRET_KEY_1234567890_ABCDEF
      - Jwt__Issuer=authservice
      - Jwt__Audience=auth_clients
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge




